# Generated by Django 5.1.3 on 2024-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='media/No_images.PNG', upload_to='movie_images'),
        ),
    ]
